baseURL = 'https://lxgr-linux.github.io'
languageCode = 'en-us'
title = 'Lxgrs Blog'
theme = 'anubis'
paginate = 10
disqusShortname = "lxgr-blog"
googleAnalytics = "G-12345"
enableRobotsTXT = true

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 1

[params]
author = "lxgr-linux"
email = "lxgr@protonmail.com"
avatar = "/assets/images/me.png"
description = "A small programmers blog"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark-without-switcher"
readMore = false
readNextPosts = 5
disableSummary = false
copyCodeButton = true
rssAsSocialIcon = true
utterancesRepo = ""
utterancesTheme = ""
utterancesIssue = ""
utterancesLabel = ""
graphcommentId = ""

#  [params.isso]
#  enabled = true
#  data = "https://comments.example.com/"
#  jsLocation = "https://comments.example.com/js/embed.min.js"
#  css = true
#  lang = "de"
#  replyToSelf = true
#  requireAuthor = true
#  requireEmail = true
#  id = "thread-id"
#  avatar = true
#  avatar-bg = "#f0f0f0"

  [params.webmentions]
  #url = "https://webmention.io/lxgr-linux.github.io_blog_/webmention"
  login = "lxgr-linux.github.io_blog_"
  pingback = true

  [[params.social]]
  id = "github"
  name = "lxgr-linux"

[markup.goldmark.renderer]
unsafe = true

